"""
Glossary of every term and abbreviation used across this repository.

Why it exists
-------------
A Track 02 review panel mixes banking, risk, compliance and engineering readers.
"Day-1 salary depletion", "four-fifths rule", "±8 pt nudge" and "p95" are each
obvious to exactly one of them. Rather than dilute the product language, the
product ships its own dictionary.

The abbreviation list was built by scanning every .py / .md / .html / .css / .js
/ .yaml file in the repo for capitalised tokens, so it tracks the code rather
than a hand-kept list that drifts. The regression suite re-runs that scan and
fails the build if a term used in the codebase is missing here.
"""

from __future__ import annotations

CATEGORIES = [
    "Banking & credit",
    "Regulatory & governance",
    "Product & scoring",
    "Responsible AI",
    "Machine learning",
    "Engineering & deployment",
    "Competition & process",
    "Units & notation",
]

# (term, expansion, category, definition, where it appears)
TERMS: list[tuple[str, str, str, str, str]] = [
    # ---------------- Banking & credit ----------------
    ("AA", "Account Aggregator", "Banking & credit",
     "RBI-licensed consent framework that lets a customer share data held at one financial institution with another, without sharing credentials. Used here to pull other-bank inflows and build a holistic income view.",
     "/multi-bank · Account Aggregator flow"),
    ("AMB", "Average Monthly Balance", "Banking & credit",
     "Mean end-of-day balance across a month. A balance cushion of 50%+ of monthly income is read as repayment headroom.",
     "Repayment capacity scorer"),
    ("Balance transfer", "", "Banking & credit",
     "Moving an existing loan from another lender to IDBI, usually at a better rate. Used as an RM lever: it retires a costlier external EMI, lowers DTI and wins the asset.",
     "Next Best Action → obligation relief"),
    ("CIBIL / Experian / Equifax / CRIF", "India's four credit bureaus", "Banking & credit",
     "The credit information companies licensed in India. The engine is bureau-agnostic — it consumes "
     "band, enquiries, utilisation, active lines and repayment history, whichever bureau supplies them.",
     "Bureau assessment"),
    ("HDFC / ICICI / SBI", "", "Banking & credit",
     "Other Indian banks, used in the simulation as the Financial Information Providers a customer's "
     "Account Aggregator consent would pull from. Illustrative only — no real institution is integrated.",
     "Account Aggregator flow"),
    ("Bureau", "Credit bureau", "Banking & credit",
     "Agency (CIBIL, Experian, Equifax, CRIF) holding a borrower's credit history. The engine consumes band, enquiries, utilisation, active lines and repayment history.",
     "Bureau assessment · Customer detail → Credit Bureau Analysis"),
    ("CASA", "Current Account / Savings Account", "Banking & credit",
     "A bank's deposit-holding retail customers. Track 02 is about converting these existing liability customers into borrowers.",
     "Problem statement"),
    ("Credit utilisation", "", "Banking & credit",
     "Revolving credit used as a share of the limit available. Above 75% the engine deducts 28 points from the bureau sub-score.",
     "Bureau assessment"),
    ("Cross-sell", "", "Banking & credit",
     "Selling an additional product to an existing customer — here, an asset product to a liability customer.",
     "Product match ranking"),
    ("Delinquency", "", "Banking & credit",
     "Falling behind on repayment. The engine scores a forward-looking 12-month delinquency risk from spending behaviour, before any loan exists.",
     "Enrichment layer"),
    ("Disposable income", "", "Banking & credit",
     "Income left after essential spend and existing obligations. The base for the affordable-EMI estimate (45% of disposable).",
     "Repayment capacity scorer"),
    ("DPD", "Days Past Due", "Banking & credit",
     "Days a payment is overdue. '30+ DPD in 12 months' is the standard delinquency flag requested from the sandbox bureau API.",
     "Sandbox field contract"),
    ("DTI", "Debt-to-Income ratio", "Banking & credit",
     "Existing EMI obligations divided by income. At or below 0.30 the engine treats new EMI capacity as clear; above 0.45 it caps headroom.",
     "Repayment capacity scorer"),
    ("EMI", "Equated Monthly Instalment", "Banking & credit",
     "The fixed monthly repayment on a loan. Every product match is gated on whether the customer's affordable EMI clears that product's minimum.",
     "Product EMI gates"),
    ("FIP", "Financial Information Provider", "Banking & credit",
     "The institution *supplying* data in the AA framework — the customer's other banks (HDFC, ICICI, SBI in the simulation).",
     "Account Aggregator flow"),
    ("FIU", "Financial Information User", "Banking & credit",
     "The institution *consuming* AA data. IDBI is the FIU in this design.",
     "AA flow · /multi-bank"),
    ("KYC", "Know Your Customer", "Banking & credit",
     "Mandatory identity verification. Referenced as a pre-filled source when converting an enquiry into an application.",
     "Next Best Action → application assist"),
    ("Liability customer", "", "Banking & credit",
     "A depositor — someone whose money the bank holds (a liability on the bank's books), as opposed to a borrower (an asset).",
     "Track 02 problem statement"),
    ("NEFT", "National Electronic Funds Transfer", "Banking & credit",
     "Indian interbank transfer rail. Appears as a transaction channel in the synthetic timeline.",
     "Transaction timeline"),
    ("RD", "Recurring Deposit", "Banking & credit",
     "A fixed monthly savings instrument. Used as an uplift lever — a standing instruction is both a cross-sell and an observable discipline signal.",
     "Uplift simulator"),
    ("RM", "Relationship Manager", "Banking & credit",
     "The bank officer who calls and converts leads. The entire product exists to protect the RM's finite calling minutes.",
     "Everywhere — RM queue, RM brief, RM workflow"),
    ("Sanction", "", "Banking & credit",
     "Formal approval of a loan. Explicitly out of scope: this system recommends, an underwriter sanctions.",
     "Governance controls"),
    ("SIP", "Systematic Investment Plan", "Banking & credit",
     "Scheduled recurring investment. Detected as a savings-transfer signal in the transaction timeline.",
     "Transaction timeline"),
    ("Tenor", "", "Banking & credit",
     "Loan duration in months. Used to convert an affordable EMI into an indicative ticket size (home 180m, auto 60m, personal 48m).",
     "Next Best Action engine"),
    ("Ticket size", "", "Banking & credit",
     "The principal amount of a loan. 'Indicative ticket' here is affordable EMI × tenor × 0.72 interest discount.",
     "Next Best Action"),
    ("Top-up", "", "Banking & credit",
     "Additional borrowing on an existing loan. Paired with balance transfer as an obligation-relief lever.",
     "Next Best Action"),
    ("Underwriter", "", "Banking & credit",
     "The risk officer who approves or declines credit. The system produces a packet for this person and never replaces them.",
     "Underwriter packet · human-in-loop disclaimer"),
    ("UPI", "Unified Payments Interface", "Banking & credit",
     "India's real-time retail payments rail. Merchant-category shares of UPI spend give the behavioural discipline signal.",
     "UPI merchant signals"),
    ("Window shopping", "", "Banking & credit",
     "High browsing with no commitment — many loan page views, no calculator use, no application. The specific waste IDBI asked Track 02 to eliminate.",
     "Window-shop Risk tier"),

    # ---------------- Regulatory & governance ----------------
    ("Adverse action", "", "Regulatory & governance",
     "A decision unfavourable to a customer that must be explainable to them. Deprioritisation here is *not* an adverse credit action — it is contact prioritisation — but every suppressed lead still carries a reason.",
     "/fairness → explainability coverage"),
    ("Business necessity", "", "Regulatory & governance",
     "The fair-lending defence that a disparity arises from a legitimate, necessary criterion (repayment capacity) rather than bias. Stated explicitly per dimension on the fairness page.",
     "Fairness audit"),
    ("Consent artefact", "", "Regulatory & governance",
     "The signed, time-boxed, purpose-limited record of a customer's AA consent. No other-bank data is fetched without a valid consent id.",
     "/api/aa/consent"),
    ("Data minimisation", "", "Regulatory & governance",
     "Collecting only what the stated purpose requires. Here: aggregated ratios, never raw statements or merchant names.",
     "/fairness → data inventory"),
    ("DPDP", "Digital Personal Data Protection Act, 2023", "Regulatory & governance",
     "India's data protection law — notice, consent, purpose limitation, minimisation and erasure obligations. Drives the consent and inventory design.",
     "/fairness · /architecture → compliance"),
    ("Human-in-the-loop", "", "Regulatory & governance",
     "A person makes the consequential decision; the model only informs it. The core compliance claim of this product.",
     "Every RM brief · governance controls"),
    ("LDAP", "Lightweight Directory Access Protocol", "Regulatory & governance",
     "Enterprise directory used for staff authentication. The demo's PIN gate maps to IDBI SSO/LDAP in production.",
     "/architecture → access control"),
    ("Purpose limitation", "", "Regulatory & governance",
     "Data collected for credit assessment may not be reused for unrelated marketing. Asserted and inventoried.",
     "/fairness → data inventory"),
    ("RBI", "Reserve Bank of India", "Regulatory & governance",
     "India's central bank and banking regulator. Licenses the AA framework and sets expectations on model explainability.",
     "/architecture → compliance"),
    ("SSO", "Single Sign-On", "Regulatory & governance",
     "Federated staff login. Production target for the RM auth gate.",
     "RM sign-in · /architecture"),

    # ---------------- Product & scoring ----------------
    ("Affordable EMI estimate", "", "Product & scoring",
     "45% of estimated monthly disposable income — the EMI the engine believes the customer can carry. Gates every product match.",
     "Scoring engine"),
    ("Behavioural discipline", "", "Product & scoring",
     "One of the three AMA dimensions: day-1 salary spend, need vs want vs luxury mix, savings transfers and bureau enquiry behaviour.",
     "Scoring engine"),
    ("Composite lead score", "", "Product & scoring",
     "0–100 blend of four pillars: repayment 33%, intent 28%, discipline 22%, delinquency safety 17%, with a bureau adjustment.",
     "Scoring engine"),
    ("Counterfactual", "", "Product & scoring",
     "A 'what if' re-score. The uplift simulator copies the customer record, applies one change, and re-runs the identical rule engine to measure the real effect.",
     "Uplift simulator · Customer detail → Uplift Simulator"),
    ("Day-1 salary spend", "", "Product & scoring",
     "Share of salary spent within 1–2 days of credit. Above 0.75 it is the strongest single delinquency predictor in the engine.",
     "Behavioural discipline scorer"),
    ("EMI gate", "", "Product & scoring",
     "The minimum affordable EMI a product requires (home ₹15,000, mortgage ₹18,000, auto ₹7,000, personal ₹3,500, consumer durable ₹2,000).",
     "Product EMI gates"),
    ("Geo stability", "", "Product & scoring",
     "Consistency between a customer's declared city and where their transactions actually occur, plus metro catchment and commute spend.",
     "Enrichment layer"),
    ("Holistic income", "", "Product & scoring",
     "IDBI-inferred income plus other-bank inflow revealed through AA. Usually the difference between 'Interested' and 'Serious'.",
     "Multi-bank view · /multi-bank"),
    ("Income confidence", "", "Product & scoring",
     "0–1 reliability of the inferred income figure. Below 0.55 the engine falls back to stated income rather than trusting the inference.",
     "Income inference"),
    ("Inferred income", "", "Product & scoring",
     "Income reconstructed from credit inflows, balance turnover and savings behaviour — not the salary the customer declared.",
     "Income inference"),
    ("Interested", "", "Product & scoring",
     "Third lead tier (composite 38–62). Digital nurture only — no RM minutes spent yet.",
     "Lead tiers"),
    ("Lead tier", "", "Product & scoring",
     "The four-way RM prioritisation: Quality Lead → Serious → Interested → Window-shop Risk.",
     "Scoring engine"),
    ("Merchant diversity", "", "Product & scoring",
     "Breadth of UPI merchant categories used. A diverse, utilities-inclusive footprint reads as a stable lifestyle.",
     "UPI merchant signals"),
    ("NBA", "Next Best Action", "Product & scoring",
     "The single highest-value thing an RM should do for this lead right now, with channel, SLA, script, RM-minute cost and expected rupee value.",
     "Next Best Action engine · /actions"),
    ("Need / want / luxury", "", "Product & scoring",
     "Three-way split of spending required by the Track 02 brief: essentials, discretionary, and luxury.",
     "Customer detail → spend chart"),
    ("Nudge", "", "Product & scoring",
     "The bounded adjustment the ML model is permitted to make to a rule-based score — at most ±8 points, and never downward for a Quality Lead.",
     "ML layer"),
    ("Product match", "", "Product & scoring",
     "Ranking of the five loan products by fit, each gated on affordable EMI: home, mortgage, auto, personal, consumer durable.",
     "Scoring engine"),
    ("Purchase intent", "", "Product & scoring",
     "One of the three AMA dimensions: page visits, calculator usage, session depth, application started, minus the window-shopping penalty.",
     "Scoring engine"),
    ("Quality Lead", "", "Product & scoring",
     "Top tier: composite ≥78 with repayment ≥62, intent ≥55, discipline ≥52 and a non-High delinquency band. 24-hour callback SLA.",
     "Lead tiers"),
    ("RAG", "Red / Amber / Green", "Regulatory & governance",
     "Traffic-light risk banding used for delinquency and bureau verdicts. In this repo RAG means the traffic-light convention, not retrieval-augmented generation.",
     "Delinquency and bureau assessments"),
    ("Repayment capacity", "", "Product & scoring",
     "One of the three AMA dimensions: disposable income, DTI, savings behaviour, employment stability, bureau strength and multi-bank income.",
     "Scoring engine"),
    ("Resilience / stress test", "", "Product & scoring",
     "Re-score under an adverse six-month scenario (DTI +12 pts, day-1 spend +18 pts, luxury +5 pts, 2 more enquiries, disposable −12%). A tier that survives is safe to underwrite.",
     "Uplift simulator"),
    ("RM queue", "", "Product & scoring",
     "Quality Lead + Serious — the ~23% of the book that earns an RM call.",
     "/ dashboard · /api/rm-queue"),
    ("Serious", "", "Product & scoring",
     "Second lead tier (composite ≥62 with dimension gates). Assisted digital journey within 48 hours.",
     "Lead tiers"),
    ("Spray and pray", "", "Product & scoring",
     "Calling every lead indiscriminately — the status quo that produces ~1% conversion.",
     "/impact → Before/After toggle"),
    ("Uplift lever", "", "Product & scoring",
     "A single executable change — AA consent, calculator walkthrough, obligation relief, savings standing instruction — whose real scoring impact is simulated.",
     "Uplift simulator"),
    ("Value per RM minute", "", "Product & scoring",
     "Expected incremental disbursal divided by the RM minutes an action costs. The ranking metric for the whole action queue.",
     "Next Best Action engine"),
    ("Window-shop Risk", "", "Product & scoring",
     "Bottom tier. Explicitly suppressed from outbound calling; returns 12 RM minutes per lead to the queue.",
     "Lead tiers · /actions"),

    # ---------------- Responsible AI ----------------
    ("DI", "Disparate impact", "Responsible AI",
     "Shorthand for the disparate impact ratio used throughout the fairness tables.",
     "/fairness"),
    ("DPO", "Data Protection Officer", "Responsible AI",
     "The officer accountable for DPDP compliance. The data inventory on the fairness page is written "
     "for this reader specifically.",
     "/fairness → data inventory"),
    ("SHAP", "SHapley Additive exPlanations", "Responsible AI",
     "A game-theoretic method for attributing a model's output to its input features. Useful to a data "
     "scientist, but not an instruction an RM can act on — which is why this build ships a counterfactual "
     "uplift simulator alongside feature contributions rather than instead of them.",
     "ML layer · contrasted on /usps"),
    ("Disparate impact ratio", "", "Responsible AI",
     "A group's selection rate divided by the highest group's selection rate. Below 0.80 it fails the four-fifths rule and requires justification or mitigation.",
     "/fairness"),
    ("Four-fifths rule", "80% rule", "Responsible AI",
     "Fair-lending convention: a group selected at less than 80% of the best-performing group's rate is a finding that must be explained.",
     "Fairness audit"),
    ("Proxy attribute", "", "Responsible AI",
     "A permitted feature that stands in for a prohibited one — surname for community, pin code for caste or religion, employment type for informal-sector workers. Each is registered with its mitigation.",
     "/fairness → proxy register"),
    ("Selection rate", "", "Responsible AI",
     "Share of a segment placed in the RM call queue. The quantity audited for parity.",
     "/fairness"),
    ("Prohibited attribute", "", "Responsible AI",
     "Gender, religion, caste, ethnicity, marital status, disability, political or union affiliation — none collected, none modelled, verified against the live feature vector on every page load.",
     "Fairness audit"),

    # ---------------- Machine learning ----------------
    ("AI", "Artificial Intelligence", "Machine learning",
     "Used here narrowly: a bounded XGBoost nudge on a deterministic rule engine, plus template/LLM generation of RM briefs. No autonomous decision-making.",
     "Product name · /architecture"),
    ("Backtest", "", "Machine learning",
     "Replaying a strategy against fixed latent propensities to isolate the effect of prioritisation. 500 Monte Carlo trials on the same population.",
     "Impact model"),
    ("CI", "Confidence interval", "Machine learning",
     "The 90% range of simulated conversion outcomes (5th to 95th percentile), reported instead of a single flattering number.",
     "Scoring engine"),
    ("Confusion matrix", "", "Machine learning",
     "Table of predicted versus actual tiers — where the classifier confuses Serious for Quality, and so on.",
     "/ml → ML credibility report"),
    ("Feature importance", "", "Machine learning",
     "How much each of the 35 input features drives the model's output. Published as part of the model card.",
     "/api/ml/model-card"),
    ("Feature vector", "", "Machine learning",
     "The 35 numbers describing one customer that the model actually sees. Notably excludes name, gender, religion and caste.",
     "Model feature set"),
    ("Guardrail", "", "Machine learning",
     "A hard constraint on model behaviour: ±8 point maximum nudge, minimum confidence threshold, and no demotion of Quality Leads.",
     "ML layer"),
    ("Hybrid scoring", "", "Machine learning",
     "Rules produce the score and the tier; ML only adjusts within guardrails. If the model is unavailable the service degrades to rules rather than failing.",
     "Scoring engine"),
    ("Latent propensity", "", "Machine learning",
     "The synthetic per-customer conversion probability used as backtest ground truth, derived from tier, composite, intent and window-shopping signals.",
     "Impact model"),
    ("LLM", "Large Language Model", "Machine learning",
     "Optional generator for the RM call brief. Falls back to a deterministic template when no API key is set, so the demo never depends on a third party.",
     "RM brief"),
    ("MAE", "Mean Absolute Error", "Machine learning",
     "Average absolute gap between predicted and actual composite score. Validation target ≤5 points.",
     "/ml → model card"),
    ("ML", "Machine Learning", "Machine learning",
     "The XGBoost layer. Deliberately subordinate to the rule engine so every tier stays explainable.",
     "ML layer · /ml"),
    ("Monte Carlo", "", "Machine learning",
     "Repeated random simulation used to produce a distribution of outcomes rather than a point estimate.",
     "Impact model"),
    ("Precision / recall", "", "Machine learning",
     "Precision: of the leads called Quality, how many were. Recall: of the true Quality leads, how many were found. Both reported per tier.",
     "/ml"),
    ("R²", "Coefficient of determination", "Machine learning",
     "Share of score variance the regressor explains — 1.0 is perfect, 0 is no better than the mean.",
     "/ml → model card"),
    ("PSI", "Population Stability Index", "Machine learning",
     "Measures how far the population being scored has drifted from the one the model was trained on, "
     "feature by feature. Conventional credit-model bands: below 0.10 stable, 0.10–0.25 investigate, "
     "above 0.25 retrain.",
     "Drift monitoring · /governance → model risk"),
    ("Calibration", "", "Machine learning",
     "Comparing a predicted rate against the rate actually observed. Here it is the tier conversion "
     "assumptions on /impact measured against RM dispositions, with the gap published in percentage points.",
     "Outcome feedback loop · /outcomes"),
    ("Feedback loop", "", "Machine learning",
     "Capturing what happened after a recommendation so the next model can learn from outcomes rather "
     "than from the rules that produced the recommendation.",
     "/outcomes"),
    ("Disposition", "", "Product & scoring",
     "What the RM records after a call: not reachable, declined, not interested, interested, application "
     "started, declined by underwriting, or loan booked. The label the next model trains on.",
     "Outcome feedback loop"),
    ("Append-only", "", "Regulatory & governance",
     "A store where records are added but never edited or deleted. A correction is a new record that "
     "supersedes the old one, so the audit trail can never be rewritten.",
     "Scoring engine"),
    ("JSONL", "JSON Lines", "Engineering & deployment",
     "One JSON object per line. Used for the outcome and audit stores because a torn final write costs "
     "a single record rather than the whole file.",
     "Append-only stores"),
    ("UTC", "Coordinated Universal Time", "Engineering & deployment",
     "The timezone every audit and outcome timestamp is written in, so records from different branches "
     "and regions order correctly.",
     "Decision audit log · Outcome feedback loop"),
    ("Degradation testing", "", "Responsible AI",
     "Removing a data source from every record and re-scoring the book to measure what actually changes — "
     "tier churn, queue size and failures — instead of claiming the system degrades gracefully.",
     "Data quality gates · /governance → data quality"),
    ("Ingest gate", "", "Regulatory & governance",
     "A rule applied before scoring: a record missing a customer ID or a stated monthly income is rejected rather "
     "than scored on defaults, and out-of-range ratios are clamped and flagged for review.",
     "/governance → data quality"),
    ("RNG", "Random Number Generator", "Machine learning",
     "The seeded generator behind the synthetic dataset, the transaction timeline and the Monte Carlo "
     "backtest. Every RNG in this build is seeded from a stable value so the same input always "
     "reproduces the same output.",
     "Synthetic dataset · Transaction timeline · Impact model"),
    ("Seed", "", "Machine learning",
     "Fixed random seed (42) that makes the dataset, the backtest and every tier reproducible — the precondition for auditability.",
     "Synthetic dataset"),
    ("Tier accuracy", "", "Machine learning",
     "Share of validation leads the classifier places in the correct tier.",
     "/ml"),
    ("XGBoost", "Extreme Gradient Boosting", "Machine learning",
     "Gradient-boosted decision tree library. Supplies the bounded nudge and the tier classifier.",
     "ML layer · Dependency manifest"),

    # ---------------- Engineering & deployment ----------------
    ("ASGI", "Asynchronous Server Gateway Interface", "Engineering & deployment",
     "The Python standard for async web servers. FastAPI is an ASGI application and Uvicorn is the ASGI "
     "server that runs it.",
     "Deployment configuration · Application server"),
    ("GPU", "Graphics Processing Unit", "Engineering & deployment",
     "Explicitly not required anywhere in this stack — scoring, training and serving all run on "
     "laptop-class CPU, which keeps the pilot's infrastructure ask small.",
     "Benchmark script · Dependency manifest"),
    ("AJAX", "Asynchronous JavaScript And XML", "Engineering & deployment",
     "Fetching a page fragment without a full reload — used for dashboard pagination and filters.",
     "static/nav.js"),
    ("API", "Application Programming Interface", "Engineering & deployment",
     "The machine-readable surface. Judge-facing endpoints are deliberately public: /api/health, /api/impact, /api/sandbox/{id}, /api/fairness, /api/usps, /api/glossary.",
     "Application routes"),
    ("API Gateway", "", "Engineering & deployment",
     "AWS managed front door (TLS, WAF, rate limiting) in the post-shortlist production design.",
     "/architecture"),
    ("AWS", "Amazon Web Services", "Engineering & deployment",
     "Target production cloud and the host of the IDBI sandbox the shortlisted teams integrate with.",
     "/architecture"),
    ("CloudWatch", "", "Engineering & deployment",
     "AWS observability service in the production design.",
     "/architecture"),
    ("CPU", "Central Processing Unit", "Engineering & deployment",
     "Benchmarks are quoted on laptop-class CPU, with no GPU dependency anywhere in the stack.",
     "Benchmark script"),
    ("CSV", "Comma-Separated Values", "Engineering & deployment",
     "Export format for the RM outreach list — the format a branch team can actually open.",
     "/api/rm-queue/export"),
    ("Docker", "", "Engineering & deployment",
     "Container format used for deployment; the ML model trains during image build.",
     "Deployment configuration"),
    ("ECS / Fargate", "Elastic Container Service", "Engineering & deployment",
     "AWS serverless container runtime proposed for the production scoring service.",
     "/architecture"),
    ("FastAPI", "", "Engineering & deployment",
     "Python web framework serving both the HTML pages and the JSON APIs.",
     "Application routes"),
    ("fpdf2", "", "Engineering & deployment",
     "Library that renders the underwriter packet PDF.",
     "Underwriter packet"),
    ("GET / POST", "HTTP methods", "Engineering & deployment",
     "GET reads (health, impact, briefs), POST writes or triggers (login, AA consent, AA fetch).",
     "Application routesroutes"),
    ("HTML / CSS / JS", "", "Engineering & deployment",
     "The UI layer — server-rendered Jinja2 templates with one hand-written stylesheet and a small vanilla-JS navigation helper. No frontend build step.",
     "User interface"),
    ("Jinja2", "", "Engineering & deployment",
     "Server-side template engine rendering every page.",
     "User interface"),
    ("joblib", "", "Engineering & deployment",
     "Serialisation format for the trained model artefacts.",
     "Trained model artefact"),
    ("JSON", "JavaScript Object Notation", "Engineering & deployment",
     "Data interchange format for the APIs and the synthetic customer store.",
     "Synthetic dataset"),
    ("p95", "95th percentile", "Engineering & deployment",
     "The latency 95% of requests beat. Single-customer scoring is ~21 ms p95; the scale KPI is under 2 s.",
     "Benchmark script"),
    ("PDF", "Portable Document Format", "Engineering & deployment",
     "Format of the underwriter packet an RM attaches to a lead record.",
     "/api/customer/{id}/underwriter-pdf"),
    ("PIN", "Personal Identification Number", "Engineering & deployment",
     "The demo RM login gate (idbi2026), overridable via the RM_DEMO_PIN environment variable.",
     "/login · RM sign-in"),
    ("Pydantic", "", "Engineering & deployment",
     "Validation layer FastAPI uses for request and response models.",
     "Dependency manifest"),
    ("pytest", "", "Engineering & deployment",
     "Test runner. The suite gates tier distribution, determinism, ML credibility and the AA uplift path.",
     "Automated regression suite"),
    ("RDS", "Relational Database Service", "Engineering & deployment",
     "AWS managed database holding scores and the audit trail in the production design.",
     "/architecture"),
    ("Render", "", "Engineering & deployment",
     "Free-tier Docker host running the public demo.",
     "Deployment configuration"),
    ("S3", "Simple Storage Service", "Engineering & deployment",
     "AWS object store for transaction batches and generated PDF packets.",
     "/architecture"),
    ("SageMaker", "", "Engineering & deployment",
     "AWS managed ML hosting proposed for the model endpoint in production.",
     "/architecture"),
    ("scikit-learn", "", "Engineering & deployment",
     "Supplies the train/validation split and evaluation metrics around the XGBoost models.",
     "ML layer"),
    ("SMS", "Short Message Service", "Engineering & deployment",
     "Low-cost nudge channel (2 RM minutes) in the action catalogue.",
     "Next Best Action engine"),
    ("TLS", "Transport Layer Security", "Engineering & deployment",
     "Encryption in transit, terminated at the API Gateway in the production design.",
     "/architecture"),
    ("URL", "Uniform Resource Locator", "Engineering & deployment",
     "Public demo address, supplied to the application as a deployment setting.",
     "Configuration"),
    ("Uvicorn", "", "Engineering & deployment",
     "ASGI server that runs the FastAPI application.",
     "Deployment configuration"),
    ("WAF", "Web Application Firewall", "Engineering & deployment",
     "Request filtering at the production edge — blocks injection and abusive traffic before it "
     "reaches the scoring service.",
     "/architecture"),

    # ---------------- Competition & process ----------------
    ("A/B test", "", "Competition & process",
     "The 4-week pilot design: a prioritised RM cohort against an undifferentiated control, on the same lead pool.",
     "/impact → pilot validation plan"),
    ("AMA", "Ask Me Anything", "Competition & process",
     "The IDBI orientation session whose stated requirements the feature set is traced against, line by line.",
     "Requirement traceability matrix"),
    ("Hack2skill", "", "Competition & process",
     "Platform hosting IDBI Innovate 2026 submissions.",
     "Submission checklist"),
    ("IDBI", "Industrial Development Bank of India", "Competition & process",
     "The bank running the challenge and the intended operator of this system.",
     "Everywhere"),
    ("KPI", "Key Performance Indicator", "Competition & process",
     "Pilot success measures: quality-segment conversion ≥32%, RM hours per booked loan −40%, window-shop false positives <15%.",
     "/architecture → pilot roadmap"),
    ("POC", "Proof of Concept", "Competition & process",
     "This build. Synthetic data, documented assumptions, production architecture designed but not deployed.",
     "Scoring engine"),
    ("PPT", "PowerPoint presentation", "Competition & process",
     "The mandatory Hack2skill submission deck, kept in input/ and regenerated by script so the "
     "demo URL and metrics never drift from the running build.",
     "input/ · Submission deck build"),
    ("Sandbox", "", "Competition & process",
     "The IDBI AWS environment that replaces synthetic data after shortlisting. Three endpoints are contracted: transactions, bureau, digital.",
     "/api/sandbox/{id} · Sandbox field contract"),
    ("SLA", "Service Level Agreement", "Competition & process",
     "The response-time promise attached to a tier: 24 hours for Quality Leads, 48 for Serious. Scheduled before discretionary work in the day plan.",
     "/actions"),
    ("Track 02", "Prospect Assist AI", "Competition & process",
     "The IDBI Innovate 2026 problem statement this repository answers: lift ~1% liability-lead conversion using behavioural signals.",
     "Everywhere"),
    ("USP", "Unique Selling Proposition", "Competition & process",
     "A capability this build has that a typical Track 02 entry does not. Catalogued with evidence links on /usps.",
     "USP catalogue · /usps"),
    ("UI", "User Interface", "Competition & process",
     "The RM-facing screens. Deliberately plain, dense and fast — built for a branch desktop, not a demo reel.",
     "User interface"),

    # ---------------- Units & notation ----------------
    ("₹ / INR", "Indian Rupee", "Units & notation",
     "All monetary figures. Written in the Indian numbering convention.",
     "Everywhere"),
    ("Crore (Cr)", "", "Units & notation",
     "10,000,000 (10 million). Portfolio value figures are quoted in crore.",
     "/impact"),
    ("Lakh", "", "Units & notation",
     "100,000. Standard Indian unit for ticket sizes.",
     "/impact"),
    ("pp", "percentage points", "Units & notation",
     "The arithmetic difference between two percentages. A move from 1% to 25% is +24 pp, not +24%.",
     "/actions · /impact"),
    ("Ratio (0–1)", "", "Units & notation",
     "Every *_ratio field is a fraction of 1, not a percentage. 0.28 means 28%.",
     "Sandbox field contract"),
]


def build_glossary() -> dict:
    entries = [
        {
            "term": t,
            "expansion": e,
            "category": c,
            "definition": d,
            "where": w,
            "search": f"{t} {e} {d} {w}".lower(),
        }
        for t, e, c, d, w in TERMS
    ]
    by_category = {
        cat: [e for e in entries if e["category"] == cat] for cat in CATEGORIES
    }
    return {
        "count": len(entries),
        "categories": [
            {"name": cat, "count": len(by_category[cat]), "entries": by_category[cat]}
            for cat in CATEGORIES
            if by_category[cat]
        ],
        "entries": entries,
        "note": (
            "Abbreviations were harvested by scanning every source file in the repository for "
            "capitalised tokens, then defined in context. The automated regression suite re-runs that scan "
            "and fails the build if a term used in the product is missing here."
        ),
    }
